services:
  backend:
    image: python:3.9-slim
    container_name: nash-backend-dev
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - FLASK_APP=web_api.py
    command: bash -c "pip install -r requirements.txt && python -m flask run --host=0.0.0.0 --port=5000 --debug"
    networks:
      - nash-network-dev

  frontend:
    image: node:18-alpine
    container_name: nash-frontend-dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
    command: sh -c "npm install && npm start"
    depends_on:
      - backend
    networks:
      - nash-network-dev
    stdin_open: true
    tty: true

networks:
  nash-network-dev:
    driver: bridge
